# damodar

In [1]:
import numpy as np

y = np.array([1,3,3,2,1,5,7, 2, 3, 4, 5])
print(np.unique(y))
print(len(np.unique(y)))


[1 2 3 4 5 7]
6


In [5]:
y = np.array([1,3,3,2,2])
one_hot = np.zeros((len(y), 4), dtype=float)
print(np.arange(len(y)))
print(y)
one_hot[np.arange(len(y)), y] = 1
print(one_hot)

[0 1 2 3 4]
[1 3 3 2 2]
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


In [ ]:
import numpy as np

def one_hot_encode(y, num_classes=None):
    """
    Convert integer labels into one-hot encoded matrix.

    Parameters:
    y : array-like, shape (N,)
        Non-negative integer labels

    num_classes : int, optional
        Total number of classes.
        If None, uses max(y) + 1

    Returns:
    np.ndarray, shape (N, K)
        One-hot encoded matrix
    """

    # Convert to NumPy array
    y = np.array(y, dtype=int)

    # Auto-detect number of classes
    if num_classes is None:
        num_classes = np.max(y) + 1

    # Validate labels
    if np.any(y < 0) or np.any(y >= num_classes):
        raise ValueError("All labels must be in range [0, num_classes-1]")

    # Create one-hot matrix
    one_hot = np.zeros((len(y), num_classes), dtype=float)

    # Vectorized assignment (no Python loop)
    one_hot[np.arange(len(y)), y] = 1.0

    return one_hot


# Example 1
y1 = [0, 2, 1]

print(one_hot_encode(y1))
# [[1. 0. 0.]
#  [0. 0. 1.]
#  [0. 1. 0.]]

# Example 2
y2 = [1, 1, 0]

print(one_hot_encode(y2, num_classes=4))
# [[0. 1. 0. 0.]
#  [0. 1. 0. 0.]
#  [1. 0. 0. 0.]]